version: '3'
services:
    nginx:
        container_name: "nginx-proxy"
        build: ./nginx
        restart: always
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./nginx/templates:/etc/nginx/templates
            - ./logs:${NGINX_LOG_DIR}
        environment:
            - NGINX_DEFAULT_HOST=${DOMAIN}
            - NGINX_LOG_DIR=${NGINX_LOG_DIR}
            - PORT=${PORT}
        depends_on:
            - frontend
            - backend
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
      expose:
        - '3306'
      ports:
        - 3306:3306
      volumes:
        - database:/var/lib/mysql
    backend:
        container_name: "kutub-backend"
        build: ./packages/backend
        restart: always
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
        volumes:
            - ./packages/backend:/home/node/app
            - backend_node_modules:/home/node/app/node_modules
            - .env:/home/node/app/.env:ro
        command: yarn start:dev
    frontend:
        container_name: "kutub-frontend"
        build: ./packages/frontend
        restart: always
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
        volumes:
            - ./packages/frontend:/home/node/app
            - frontend_node_modules:/home/node/app/node_modules
            - .env:/home/node/app/.env:ro

volumes:
  database:
  frontend_node_modules:
  backend_node_modules: