version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  frontend-unit-tests:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.15'
      - run:
          name: Run Unit Tests
          command: |
            cd packages/frontend
            yarn install
            yarn test
workflows:
  frontend:
    jobs:
      - frontend-unit-tests